### ISSUE TITLE
_BASE_CONFIG_: cfgs/dataset_configs/da_kitti_dataset_mt.yaml can not find

### ISSUE THREAD

**Issue by wanghangege** [WoodwindHu/DTS#2]
hello, thanks for your outstanding work, I meet a problems as follow, can you help me?

Traceback (most recent call last):
  File "/home/su/domain_sift/DTS/tools/../pcdet/config.py", line 81, in cfg_from_yaml_file
    merge_new_config(config=config, new_config=new_config)
  File "/home/su/domain_sift/DTS/tools/../pcdet/config.py", line 69, in merge_new_config
    merge_new_config(config[key], val)
  File "/home/su/domain_sift/DTS/tools/../pcdet/config.py", line 56, in merge_new_config
    with open(new_config['_BASE_CONFIG_'], 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cfgs/dataset_configs/da_kitti_dataset_mt.yaml'
Traceback (most recent call last):
  File "/home/su/soft_backup/pycharm-community-2022.2.2/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 828, in trace_dispatch
    if main_debugger.in_project_scope(frame.f_code.co_filename):
  File "/home/su/soft_backup/pycharm-community-2022.2.2/plugins/python-ce/helpers/pydev/pydevd.py", line 612, in in_project_scope
    return pydevd_utils.in_project_roots(filename)
AttributeError: 'NoneType' object has no attribute 'in_project_roots'

Process finished with exit code 1

**Comment by WoodwindHu** [comment]
Sorry for missing the file, I've updated the yaml file in the latest commit.

**Comment by wanghangege** [comment]
Hi, an offensive question for you guys, can you reproduce your basic results based only on your uploaded repositories? I find it difficult to reproduce this repositoriy, there will be some code problems, can you practice to answer my question? In addition, I reproduced ST3D your code based, there is no problem.

**Comment by WoodwindHu** [comment]
Sorry for the poorly organized code, we are out of GPU thus I can't practice first before publishing the code. I borrowed a machine today and fixed bugs by reruning nus->kitti task with secondiou. It should work now.

**Comment by wanghangege** [comment]
thank you，very much
